BobTheBuidler/ez-a-sync

a_sync/__init__.py, a_sync/primitives/__init__.py, a_sync/primitives/_loggable.py, a_sync/primitives/locks/__init__.py, a_sync/primitives/locks/counter.py, a_sync/primitives/locks/event.py
feat: debug logging enabled version of asyncio.Event
feat: CounterLock primitive
=> feat: New primitives

a_sync/utils/__init__.py
Added new `as_completed_mapping` and `gather_mapping` functions.
They work as you'd expect based on the standard asyncio implementations.
=> feat: mapping utils

a_sync/_helpers.py
couldn't stack decorators, now you can
=> fix: conflict between alru_cache and a_sync.future

a_sync/future.py
had issues with bound methods, now we don't
=> Fix: future bound

a_sync/primitives/locks/__init__.py
`from a_sync import PrioritySemaphore`
=> feat: import PrioritySemaphore to top-level module

a_sync/primitives/queue.py
Queue.get now supports multiple results with a kwarg
=> feat: Queue.get with multiple results

a_sync/modified.py
now we use functools.update_wrapper
=> fix: ASyncFunction.__module__ not updated to wrapped

a_sync/_meta.py, a_sync/decorator.py, a_sync/modified.py, a_sync/property.py
woohoo, finally! your ide can parse it all
=> feat: proper type checking for decorated fns

a_sync/task.py, a_sync/utils/as_completed.py, a_sync/utils/gather.py
=> fix: TaskMapping dict implementation

a_sync/_helpers.py, a_sync/exceptions.py
raise from None and init properly
=> fix: SyncModeInAsyncContextError

a_sync/task.py, a_sync/utils/__init__.py
TaskMapping now works with ASyncMethodDescriptor type input
=> feat: TaskMapping support ASyncMethodDescriptor

a_sync/modified.py
pass any relevant kwargs to the created TaskMapping object
=> feat: ASyncFunction map kwargs

a_sync/_task.py, a_sync/primitives/queue.py, a_sync/task.py
* feat: create_task log_destroyed_pending kwarg
* feat: better exceptions by pulling true exc out of subtask
* fix: pass _name to queue
* fix: hide task destroyed logs since we expect that behavior
* chore: refactor TaskMapping
=> fix: Loose ends

a_sync/task.py
sum([]) = 0
any([]) = False
all([]) = True
min([]): ValueError: min() arg is an empty sequence
max([]): ValueError: max() arg is an empty sequence
=> feat: TaskMapping handle empty iterables the same way as builtins do

a_sync/exceptions.py, a_sync/task.py
works as intended now in all known cases but 1 edge case with multi-iterables
=> fix: mapping is empty

a_sync/_typing.py, a_sync/a_sync/function.py
now bound methods type check correctly
=> feat(mypy): more overloads on ASyncDecorator

a_sync/_typing.py, a_sync/asyncio/create_task.py, a_sync/executor.py, a_sync/primitives/locks/event.py, a_sync/primitives/queue.py
new docstrings + added substance
=> revised pr

a_sync/a_sync/method.py, a_sync/a_sync/property.py
inherit the docs from whatever fn is wrapped
=> feat(docs): inherit docs for HiddenMethodDescriptor

a_sync/a_sync/_kwargs.pyx
Reverts BobTheBuidler/ez-a-sync#368
=> Revert "feat: optimize _kwargs.pyx"

a_sync/_smart.py
This was a weird edge case that is only relevant if you're running multiple loops in multiple threads
=> fix: cant make weak reference to None

a_sync/iter.pyx, tests/test_iter.py
=> fix: iterator `__init_subclass__` when subclass uses TypeVar

a_sync/primitives/locks/counter.pxd, a_sync/primitives/locks/counter.pyx
Much faster than iterating across all waiters
=> feat: use heap in CounterLock

a_sync/_smart.py, tests/test_smart.py
This reverts commit 8bc2aba1d41b91dbfc699950e80ed9e6d748a051.
Also adds a new test for the failure case.
=> Revert "feat: speed up SmartTask and SmartFuture init (#433)"

a_sync/primitives/queue.py
but with less cpu usage than before
=> feat: re-enable smart processing queue heap sorting

a_sync/_smart.pyx, a_sync/a_sync/_meta.py, a_sync/a_sync/modifiers/manager.pyx, a_sync/a_sync/property.pyx, a_sync/exceptions.py, a_sync/executor.py, a_sync/future.py, a_sync/iter.pyx, a_sync/primitives/locks/event.pyx, a_sync/primitives/locks/prio_semaphore.pyx, a_sync/primitives/locks/semaphore.pyx, a_sync/primitives/queue.py, tests/primitives/test_queue.py
too many uses of `super` throughout the library, I'm replacing them with direct calls to the things we want to access
=> feat: less super

tests/a_sync/test_property.py
These failing test cases would have prevented my merging of one of last night's PRs.
Next time they will lol
=> feat(test): test ASyncProperty map methods

a_sync/a_sync/property.pyx, tests/a_sync/test_property.py
todo: write a test before merging this
=> fix: TaskMapping not defined

a_sync/asyncio/igather.pyx
This would cause ugly logs at script end, now it won't
=> fix: attribute error in cigather cancellation handler

.github/workflows/release.yaml
=> feat(cicd): build wheels for pypi

a_sync/primitives/locks/prio_semaphore.pxd, a_sync/primitives/locks/prio_semaphore.pyx
change a list to a set to make removals fast
important because of how many calls go thru this snippet
=> feat: optimize PrioritySemaphore accesses
